### ISSUE TITLE
Spell deserves an 0.1.0 release

### ISSUE THREAD

**Issue by jtmoulia** [MyMedsAndMe/spell#37]
- [ ] Bump version numbers
- [ ] Create a github release w/ changelog
- [ ] Update hex.pm package
- [ ] Update hexdocs.pm documentation

I could handle this unless someone is excited about it.

**Comment by yelps** [comment]
Yep, that would be great. Can we merge the open pull requests before? Also I wonder if we want to close out some of the issues and the bug before creating the release.

**Comment by jtmoulia** [comment]
>  Can we merge the open pull requests before?

Yes, we can definitely merge the PRs, tho to be clear: am I in charge of merging these? I'm a bit fuzzy on responsibilities at this point, and have been more hands off ;)

> Also I wonder if we want to close out some of the issues and the bug before creating the release.

Personally, barring show-stopper bugs I'd prefer more releases rather than less. It'll get the code out and help us get feedback. Issues can be rolled into future releases.

Are there particular issues that should definitely be in an 0.1.0 release?

**Comment by yelps** [comment]
Sorry @jtmoulia for coming back on this only now. We were pretty busy working on the new platform using Spell. But I have to say it works quite nicely. :) 

I agree, let's get the first release out. The pull requests have been merged. Since it's the first release and you did nearly all of the work, I will leave the honour with you this time. :)
